src/payments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views as payment_views

from . import views

urlpatterns = [

    path('view_invoice/<int:pk>/', payment_views.InvoiceDetailView.as_view(), name='invoice-detail-view'),
    path('make_payment/<int:pk>/', payment_views.MakePayment.as_view(), name='make-payment'),
    path('invoice_list_user/', payment_views.InvoiceListUser.as_view(), name='invoice-list-user'),
    path('invoice_list_all/', payment_views.InvoiceListAll.as_view(), name='invoice-list-all'),
    path('payment_list/', payment_views.PaymentList.as_view(), name='payment-list'),
    path('cash_payment/', payment_views.MakeCashPayment, name='cash-payment-staff')

    # path('pay/', payment_views.LogoutView.as_view(template_name='accounts/logout.html'), name='pay-invoice'),

]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as account_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('records/', include('records.urls')),
    path('appointments/', include('appointments.urls')),
    path('', account_views.login),
    path('portals/', include('portals.urls')),
    path('payments/', include('payments.urls')),
    path('reports/', include('reports.urls')),


]

src/payments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.admin.utils import timezone
from django.shortcuts import reverse


# When records and payments are merged, we may want to integrate a record to an invoice so they're linked.


# Create your models here.
class Invoice(models.Model):
    # invoice number is it's primary key
    patient = models.ForeignKey(User, on_delete=models.CASCADE)
    amount_owed = models.DecimalField(decimal_places=2, max_digits=8, )
    amount_billed = models.DecimalField(decimal_places=2, max_digits=8)
    date_billed = models.DateField(default=timezone.now)
    # prev_amount_owed = models.DecimalField(decimal_places=2, max_digits=8, )

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #
    #     if self.amount_owed > self.amount_billed:
    #         self.amount_owed = self.amount_owed
    #         self.amount_owed = 0

    def amount_owed_as_string(self):
        return str(self.amount_owed)

    def __str__(self):
        return str(self.pk) + " - " + str(self.amount_billed)


class Payment(models.Model):
    # payment_method = models.CharField(max_length=15)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    payment_amount = models.DecimalField(decimal_places=2, max_digits=8)

    def __str__(self):
        return str(self.invoice.pk) + " - " + str(self.payment_amount)

    def get_absolute_url(self):
        return reverse('invoice-list-all')

src/payments/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class PaymentForm(forms.Form):
    payment_amount = forms.DecimalField(max_digits=8, decimal_places=2, min_value=0)
    invoice_number = forms.IntegerField(min_value=0)
    class Meta:
        model = models.Payment

        fields = [
            'payment_amount',
            'invoice_number',
        ]

src/payments/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, CreateView
from . import models as payment_models
from . import forms as payment_forms
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, AccessMixin
from .models import Payment, Invoice
from django.contrib.auth.models import User, Group
from django.urls import reverse_lazy
from .forms import PaymentForm


# test function
def user_belongs_to_staff_group(user):
    if user in Group.objects.get(name='Staff').user_set.all():
        return True
    else:
        return False


# secured
class PaymentList(UserPassesTestMixin, ListView):
    model = Payment

    ordering = ['-Payment.invoice.pk']
    template_name = 'payment_list.html'

    def test_func(self):
        if self.request.user in Group.objects.get(name='Patient').user_set.all():
            return True
        else:
            return False

    def get_queryset(self):
        return Payment.objects.filter(invoice__patient__pk=self.request.user.pk).all()


# secured
class MakePayment(UserPassesTestMixin, DetailView):
    model = Invoice
    template_name = 'make_payment.html'

    def test_func(self):
        if self.request.user in Group.objects.get(name='Patient').user_set.all():
            return True
        else:
            return False


# secured
class InvoiceListAll(UserPassesTestMixin, ListView):

    def test_func(self):
        if self.request.user in Group.objects.get(name='CEO').user_set.all() or self.request.user in Group.objects.get(
                name='Staff').user_set.all():
            return True
        else:
            return False

    model = Invoice
    ordering = ['date_billed']
    template_name = 'invoice_list_all.html'


class InvoiceListUser(UserPassesTestMixin, ListView):

    def test_func(self):
        if self.request.user in Group.objects.get(name='Patient').user_set.all():
            return True
        else:
            return False

    model = Invoice
    ordering = ['date_billed']
    template_name = 'invoice_list_user.html'


# secured
@login_required()
@user_passes_test(user_belongs_to_staff_group)
def MakeCashPayment(request, ):
    if request.method == 'POST':
        form = payment_forms.PaymentForm(request.POST)
        if form.is_valid():
            try:
                form = form.clean()
                # updating invoice information
                updated_invoice = payment_models.Invoice.objects.get(pk=form.get('invoice_number'))

                prev_amount_owed = updated_invoice.amount_owed

                new_amount_owed = prev_amount_owed - form.get('payment_amount')

                if new_amount_owed < 0 or new_amount_owed >= prev_amount_owed:

                    messages.add_message(request, messages.WARNING,
                                         'Amount can not be negative, greater than or the same as the previous amount owed.')

                    return redirect('cash-payment')
                else:

                    updated_invoice.amount_owed = new_amount_owed

                    # creating new cash payment
                    Payment(invoice=updated_invoice, payment_amount=form.get('payment_amount'),).save()
                    updated_invoice.save()
                    messages.add_message(request, messages.SUCCESS, 'Payment Successful. Amount Owed Updated.')
            except:

                messages.add_message(request, messages.WARNING, 'Something Went Wrong. Try Again')

            return redirect('invoice-list-all')
    else:
        form = payment_forms.PaymentForm()

    context = {'form': form}
    return render(request, 'cash_payment.html', context=context)





## Unsuccessful attempt to turn cash payments into a Class Based View
# class MakeCashPayment(UserPassesTestMixin, CreateView):
#     model = Payment
#     template_name = 'cash_payment.html'
#     success_message = "Payment was created successfully"
#     # form_class = PaymentForm
#     fields = [
#         'invoice',
#         'payment_amount'
#     ]
#
#     def post(self, request, *args, **kwargs):
#         try:
#             form = PaymentForm(request.POST)
#             if form.is_valid():
#                 new_invoice = Invoice.objects.get(invoice=form.invoice_number)
#                 original_amount_owed = new_invoice.amount_owed
#                 if original_amount_owed >= form.payment_amount:
#                     new_invoice.amount_owed = original_amount_owed - form.payment_amount
#                     new_invoice.save()
#                     Payment(payment_amount=form.payment_amount, invoice=new_invoice)
#
#         except:
#             messages.add_message(request, level=messages.WARNING, message='Something went wrong. Please Try Again.')
#             return reverse_lazy('cash-payment-staff')
#
#         return reverse_lazy('portal')
#
#     # def post(self, request, *args, **kwargs):
#     #     form = BookCreateForm(request.POST)
#     #     if form.is_valid():
#     #         book = form.save()
#     #         book.save()
#     #         return HttpResponseRedirect(reverse_lazy('books:detail', args=[book.id]))
#     #     return render(request, 'books/book-create.html', {'form': form})
#
#     def test_func(self):
#         return user_belongs_to_staff_group(self.request.user)


class InvoiceDetailView(DetailView):
    model = Invoice
    template_name = 'view_invoice.html'
    extra_context = {}

src/payments/templates/cash_payment.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="card card-primary">
        <div class="card-header">
            <h2>Cash Payment</h2>
        </div>



            <form class="float-right m-4" method="POST">{% csrf_token %}
        <fieldset class="form-group">
            <legend class=""></legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class=" btn btn-secondary float-right" type="submit">Pay</button>
            <small class="text-muted m-2">

            </small>
        </div>

    </form>
        </div>




{% endblock content %}

src/payments/templates/invoice_list.html
{% extends "base.html" %}

{% block content %}



    <div class="card p-4 float">
        <div class="card-header mb-3"><h3>Invoices - {{ user.get_full_name }}</h3></div>



                <div class="card">


                    <div class="list-group">
                        <div  class="list-group-item list-group-item-action active disabled">
                            <p class="float-left">Invoice Number</p>
                            <p class="float-right">Amount Owed</p>

                        </div>
                    {% for invoice in user.invoice_set.all %}
                        <a href="{% url 'make-payment' pk=invoice.pk %}" class="list-group-item list-group-item-action
                                    {% if invoice.amount_owed <= 0 %} disabled {% endif %}">
                        <p class="float-left">{{ invoice.pk}}</p>
                        <p class="float-right">${{ invoice.amount_owed }}</p>
                        </a>
                    {% endfor %}

                    </div>


                </div>



    </div>

{% endblock content %}

src/payments/templates/invoice_list_all.html
{% extends "base.html" %}
{% block content %}




            <div class="card p-4 float">
                <div class="card-header mb-3"><h3>Invoices - All</h3></div>
                <div class="card">
                    <div class="list-group">
                        <div class="list-group-item list-group-item-action active disabled">
                            <p class="float-left">Invoice Number</p>
                            <p class="float-right">Amount Owed</p>
                        </div>
                        {% for invoice in object_list %}
                            <a href="{% url 'invoice-detail-view' pk=invoice.pk %}" class="list-group-item list-group-item-action
                                    {% if invoice.amount_owed <= 0 %} disabled {% endif %}">
                                <p class="float-left">{{ invoice.pk }}</p>
                                <p class="float-right">${{ invoice.amount_owed }}</p>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>



    


{% endblock content %}

src/payments/templates/invoice_list_user.html
{% extends "base.html" %}

{% block content %}



    <div class="card p-4 float">
        <div class="card-header mb-3"><h3>Invoices - {{ user.get_full_name }}</h3></div>



                <div class="card">


                    <div class="list-group">
                        <div  class="list-group-item list-group-item-action active disabled">
                            <p class="float-left">Invoice Number</p>
                            <p class="float-right">Amount Owed</p>

                        </div>
                    {% for invoice in user.invoice_set.all %}
                        <a href="{% url 'invoice-detail-view' pk=invoice.pk %}" class="list-group-item list-group-item-action
                                    {% if invoice.amount_owed <= 0 %} disabled {% endif %}">
                        <p class="float-left">{{ invoice.pk}}</p>
                        <p class="float-right">${{ invoice.amount_owed }}</p>
                        </a>
                    {% endfor %}

                    </div>


                </div>



    </div>

{% endblock content %}

src/payments/templates/make_payment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="card card-primary">
        <div class="card-header">
            <h2>Make a Payment</h2>
        </div>
        <div class="float-right list-group-item">
            <p class="font-weight-bold float-left p-0 m-0">Invoice Number</p>
            <p class="font-weight-bold float-right p-0 m-0">{{ object.pk }}</p>
        </div>

        <div class="float-right list-group-item">
            <p class="font-weight-bold float-left p-0 m-0">Amount Billed</p>
            <p class="font-weight-bold float-right p-0 m-0">${{ object.amount_billed }}</p>
        </div>

        <div class="float-right list-group-item">
            <p class="font-weight-bold float-left p-0 m-0">Amount Owed</p>
            <p class="font-weight-bold float-right p-0 m-0">${{ object.amount_owed }}</p>
        </div>



        <div class="float-right list-group-item">
            <!-- Set up a container element for the button -->
            <div id="paypal-button-container"></div>
        </div>

        <div class="float-right list-group-item">
            <a href="{% url 'invoice-list-user'%}"><button type="button" class="btn btn-primary float-right">Go back</button></a>
        </div>

    </div>
    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AeFSJDq8sonOdMT62SM-B040Eo4YWi6IS6xsPqDe-eamtEbGs9Jtbf5AbtwjnPC45LjFPOCa4sNoHEIt&currency=USD&disable-funding=credit&commit=false"></script>

    <script>
        // Render the PayPal button into #paypal-button-container

        paypal.Buttons({

            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: {{ object.amount_owed_as_string }}
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    // Show a success message to the buyer

                    alert('Transaction completed by ' + details.payer.name.given_name + '!');

                });

            }


        }).render('#paypal-button-container');
    </script>


{% endblock content %}

src/payments/templates/payment_list.html
{% extends "base.html" %}

{% block content %}



    <div class="card p-4 float">
        <div class="card-header mb-3"><h3>Payments on {{ user.get_full_name }}'s Account</h3></div>



                <div class="card">


                    <div class="list-group">
                        <div  class="list-group-item list-group-item-action active disabled">
                            <p class="float-left">Invoice Number</p>
                            <p class="float-right">Payment Amount</p>

                        </div>
                    {% for payment in object_list %}
                        <a href="{% url 'invoice-detail-view' pk=payment.invoice.pk %}" class="list-group-item list-group-item-action">
                        <p class="float-left">{{ payment.invoice.pk}}</p>

                        <p class="float-right">${{ payment.payment_amount }}</p>
                        </a>
                    {% endfor %}

                    </div>


                </div>



    </div>

{% endblock content %}

src/payments/templates/view_invoice.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="card card-light shadow-sm p-2" style="max-height: 50rem;">


        <div class="card-header">
            <div class="row ml-1">
                <h1>Invoice - {{ object.patient.get_full_name }}</h1>
            </div>
            <div class="row ml-1">
                <p>Issued - {{ object.date_billed|date:"F d, Y" }}</p>
            </div>
        </div>


        <div class="card-body m-0">
            <ul class="list-group">

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Patient Name</p>
                    <p class="font-weight-bold float-right p-0 m-0">{{ object.patient.get_full_name }}</p>
                </div>

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Invoice Number</p>
                    <p class="font-weight-bold float-right p-0 m-0">{{ object.pk }}</p>
                </div>

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Amount Billed</p>
                    <p class="font-weight-bold float-right p-0 m-0">${{ object.amount_billed }}</p>
                </div>

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Amount Owed</p>
                    <p class="font-weight-bold float-right p-0 m-0">${{ object.amount_owed }}</p>
                </div>

                <div class="float-right list-group-item">
                   {% if  "Staff" in user.groups.all.0.name or "Staff" in user.groups.all.1.name or "Staff" in user.groups.all.2.name or "Staff" in user.groups.all.3.name or "Staff" in user.groups.all.4.name or "Staff" in user.groups.all.5.name %}
                        <a href="{% url 'cash-payment-staff' %}"><button class="btn btn-primary float-right">Take Cash Payment</button></a>
                {% endif %}
                    {% if 'Patient' in user.groups.all.0.name or 'Patient' in user.groups.all.1.name or 'Patient' in user.groups.all.2.name or 'Patient' in user.groups.all.3.name or 'Patient' in user.groups.all.4.name or 'Patient' in user.groups.all.5.name  %}
                        <a href="{% url 'make-payment' pk=object.pk %}"><button class="btn btn-primary float-right">Pay</button></a>
                    {% endif %}


                </div>


            </ul>





        </div>
    </div>


    </div>

{% endblock content %}