src/reports/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views as reports_views


urlpatterns = [
    # path('reports_list/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('', reports_views.ReportListView.as_view(), name='report-list'),
    path('<int:pk>/', reports_views.ReportDetailView.as_view(), name='report'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as account_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('records/', include('records.urls')),
    path('appointments/', include('appointments.urls')),
    path('', account_views.login),
    path('portals/', include('portals.urls')),
    path('payments/', include('payments.urls')),
    path('reports/', include('reports.urls')),


]

src/reports/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.utils.timezone import now
from django.template.defaultfilters import slugify


# Models aparently have no way of filtering which users reports can be made for.
# The class below allows reports to be made for any user.
# This isn't problematic for now and can be used to promote scalability later.
class Report(models.Model):
    user = models.ForeignKey(User, limit_choices_to={'groups': 1, }, on_delete=models.CASCADE)
    start_date = models.DateField(default=now())
    end_date = models.DateField(default=now())
    health_service_income = models.PositiveIntegerField(default=0)
    patients_seen = models.SmallIntegerField()

    # When called, report will print out the name of the user (Doctor) it is associated with.
    def __str__(self):
        return self.user.__str__()

    def get_absolute_url(self):
        return reverse('report-list')

# Filtering Example
# Aparently django doesn't have built in methods to prevent
# class Parent(models.Model):
#   name = models.CharField(max_length=255)
#   favoritechild = models.ForeignKey("Child", blank=True, null=True)
#
#   def save(self, force_insert=False, force_update=False):
#     if self.favoritechild is not None and self.favoritechild.myparent.id != self.id:
#       raise Exception("You must select one of your own children as your favorite")
#     super(Parent, self).save(force_insert, force_update)

src/reports/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
# Create your views here.
from django.contrib.auth.models import User, Group
from .models import Report
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, AccessMixin



class ReportListView(UserPassesTestMixin, ListView):
    #################################################################################################
    # The logic here is handled in the view. all Users are passed in, but only those with
    # reports associated with their accounts are shown in the list. This was done this way to save time
    # A good deal of time was spent attempting to do this by only passing in a model containing Users
    # with a report to their name. This should be changed later to allow better efficiency with
    # a large number of users
    # This SO post was the inspiration for this solution
    # https://stackoverflow.com/questions/232435/how-do-i-restrict-foreign-keys-choices-to-related-objects-only-in-django
    #################################################################################################

    model = User



    # DEFAULT BEHAVIOR
    # looks for template with naming structure of <app>/<model>_<viewtype>.html
    # in this case it's looking for blogapp/post_list
    # DEFAULT BEHAVIOR
    # The naming here is slightly off of the default name structure.
    # I didn't look too deep into it, but this works.
    template_name = 'reports/reports_list.html'

    # by default, in the template Django is looking for something named {{ object_list }}.
    # The method for changing it is below if we wanted it to be called {{ users }}.
    # context_object_name = 'users'

    # I've put them in alphabetical order here. this is the order the object_list will
    # be given to the template. it can be sorted by any attribute of the model (User in this case)
    ordering = ['-last_name']

    # This allows for pagination. if you've gone through a tutorial, this should be self explanatory.
    # if not, check this: https://youtu.be/acOktTcTVEQ
    # paginate_by = 15
    def get_queryset(self):
        return User.objects.filter(groups=1)

    def test_func(self):
        if self.request.user in Group.objects.get(name='CEO').user_set.all():
            return True
        else:
            return False





class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/report.html'
    context_object_name = 'report'

    def test_func(self):
        if self.request.user in Group.objects.get(name='CEO').user_set.all():
            return True
        else:
            return False

src/reports/templates/reports/report.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="card card-light shadow-sm p-2" style="max-height: 50rem;">


        <div class="card-header">
            <div class="row ml-1">
                <h1>Report - {{ report.user.get_full_name }}</h1>
            </div>
            <div class="row ml-1">
                <p>{{ report.start_date|date:"F d" }} - {{ report.start_date|date:"F d, Y" }}</p>
            </div>
        </div>


        <div class="card-body m-0">
            <ul class="list-group">

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Patients Seen</p>
                    <p class="font-weight-bold float-right p-0 m-0">{{ report.patients_seen }}</p>
                </div>

                <div class="float-right list-group-item">
                    <p class="font-weight-bold float-left p-0 m-0">Health Service Income</p>
                    <p class="font-weight-bold float-right p-0 m-0">${{ report.health_service_income }}</p>
                </div>




            </ul>


        </div>
    </div>


    </div>

{% endblock content %}

src/reports/templates/reports/reports_list.html
{% extends "base.html" %}

{% block content %}



    <div class="card p-4 float">
        <div class="card-header mb-3"><h3>Reports</h3></div>
        {% for object in object_list %}



                <div id="acordian">
                    <div class="card">

                        <button id=""  class="card-header btn btn-link collapsed" data-toggle="collapse"
                                data-target="#{{ object.username }}"
                                aria-expanded="false" aria-controls="{{ object.username }}">

                            <p class="float-left">{{ object.get_full_name }}</p>
                            <span class="badge badge-primary badge-pill float-right">{{ object.report_set.count }}</span>

                        </button>


                        <div id="{{ object.username }}"  class="card-body collapse" >
                            {% for report in object.report_set.all %}

                                <ul id="" class="list-group">
                                    <a id="{% url 'report' report.id %}" href="{{ report.id }}" class="list-group-item list-group-item-action">{{ report }}</a>
                                </ul>

                            {% endfor %}
                        </div>


                    </div>
                </div>

        {% endfor %}
    </div>

{% endblock content %}